"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_instance_sdk
from kafka_instance_sdk.model.consumer import Consumer
from kafka_instance_sdk.model.consumer_group_metrics import ConsumerGroupMetrics
from kafka_instance_sdk.model.consumer_group_state import ConsumerGroupState
globals()['Consumer'] = Consumer
globals()['ConsumerGroupMetrics'] = ConsumerGroupMetrics
globals()['ConsumerGroupState'] = ConsumerGroupState
from kafka_instance_sdk.model.consumer_group_all_of import ConsumerGroupAllOf


class TestConsumerGroupAllOf(unittest.TestCase):
    """ConsumerGroupAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumerGroupAllOf(self):
        """Test ConsumerGroupAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsumerGroupAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
