"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_instance_sdk
from kafka_instance_sdk.model.offset_type import OffsetType


class TestOffsetType(unittest.TestCase):
    """OffsetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOffsetType(self):
        """Test OffsetType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OffsetType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
