"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_instance_sdk
from kafka_instance_sdk.model.list_deprecated_all_of import ListDeprecatedAllOf


class TestListDeprecatedAllOf(unittest.TestCase):
    """ListDeprecatedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDeprecatedAllOf(self):
        """Test ListDeprecatedAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListDeprecatedAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
