"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_mgmt_sdk
from kafka_mgmt_sdk.model.supported_kafka_size_bytes_value_item import SupportedKafkaSizeBytesValueItem
globals()['SupportedKafkaSizeBytesValueItem'] = SupportedKafkaSizeBytesValueItem
from kafka_mgmt_sdk.model.kafka_request_all_of import KafkaRequestAllOf


class TestKafkaRequestAllOf(unittest.TestCase):
    """KafkaRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKafkaRequestAllOf(self):
        """Test KafkaRequestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KafkaRequestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
