"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_mgmt_sdk
from kafka_mgmt_sdk.model.region_capacity_list_item import RegionCapacityListItem
globals()['RegionCapacityListItem'] = RegionCapacityListItem
from kafka_mgmt_sdk.model.cloud_region import CloudRegion


class TestCloudRegion(unittest.TestCase):
    """CloudRegion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRegion(self):
        """Test CloudRegion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudRegion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
