# flake8: noqa

"""
    Red Hat Openshift SmartEvents Fleet Manager

    The API exposed by the fleet manager of the SmartEvents service.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: openbridge-dev@redhat.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from smart_events_management_sdk.api_client import ApiClient

# import Configuration
from smart_events_management_sdk.configuration import Configuration

# import exceptions
from smart_events_management_sdk.exceptions import OpenApiException
from smart_events_management_sdk.exceptions import ApiAttributeError
from smart_events_management_sdk.exceptions import ApiTypeError
from smart_events_management_sdk.exceptions import ApiValueError
from smart_events_management_sdk.exceptions import ApiKeyError
from smart_events_management_sdk.exceptions import ApiException
