"""
    Service Registry Management API

    Service Registry Management API is a REST API for managing Service Registry instances. Service Registry is a datastore for event schemas and API designs, which is based on the open source Apicurio Registry project.  # noqa: E501

    The version of the OpenAPI document: 0.0.6
    Contact: rhosak-eval-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_service_registry_mgmt_sdk
from rhoas_service_registry_mgmt_sdk.model.registry_instance_type_value import RegistryInstanceTypeValue
from rhoas_service_registry_mgmt_sdk.model.registry_status_value import RegistryStatusValue
globals()['RegistryInstanceTypeValue'] = RegistryInstanceTypeValue
globals()['RegistryStatusValue'] = RegistryStatusValue
from rhoas_service_registry_mgmt_sdk.model.root_type_for_registry import RootTypeForRegistry


class TestRootTypeForRegistry(unittest.TestCase):
    """RootTypeForRegistry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRootTypeForRegistry(self):
        """Test RootTypeForRegistry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RootTypeForRegistry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
