"""
    Service Registry Management API

    Service Registry Management API is a REST API for managing Service Registry instances. Service Registry is a datastore for event schemas and API designs, which is based on the open source Apicurio Registry project.  # noqa: E501

    The version of the OpenAPI document: 0.0.6
    Contact: rhosak-eval-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_service_registry_mgmt_sdk
from rhoas_service_registry_mgmt_sdk.api.registries_api import RegistriesApi  # noqa: E501


class TestRegistriesApi(unittest.TestCase):
    """RegistriesApi unit test stubs"""

    def setUp(self):
        self.api = RegistriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_registry(self):
        """Test case for create_registry

        """
        pass

    def test_delete_registry(self):
        """Test case for delete_registry

        Delete a Registry instance  # noqa: E501
        """
        pass

    def test_get_registries(self):
        """Test case for get_registries

        """
        pass

    def test_get_registry(self):
        """Test case for get_registry

        Get a Registry instance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
