"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.sso_provider_all_of import SsoProviderAllOf


class TestSsoProviderAllOf(unittest.TestCase):
    """SsoProviderAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSsoProviderAllOf(self):
        """Test SsoProviderAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SsoProviderAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
