"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.error import Error
globals()['Error'] = Error
from rhoas_kafka_mgmt_sdk.model.error_list_all_of import ErrorListAllOf


class TestErrorListAllOf(unittest.TestCase):
    """ErrorListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorListAllOf(self):
        """Test ErrorListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
