"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.values import Values
globals()['Values'] = Values
from rhoas_kafka_mgmt_sdk.model.range_query import RangeQuery


class TestRangeQuery(unittest.TestCase):
    """RangeQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRangeQuery(self):
        """Test RangeQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RangeQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
