"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.supported_kafka_instance_type_sizes_inner import SupportedKafkaInstanceTypeSizesInner
globals()['SupportedKafkaInstanceTypeSizesInner'] = SupportedKafkaInstanceTypeSizesInner
from rhoas_kafka_mgmt_sdk.model.supported_kafka_instance_type import SupportedKafkaInstanceType


class TestSupportedKafkaInstanceType(unittest.TestCase):
    """SupportedKafkaInstanceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedKafkaInstanceType(self):
        """Test SupportedKafkaInstanceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupportedKafkaInstanceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
