"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dimakis_test_kafka_mgmt_sdk
from dimakis_test_kafka_mgmt_sdk.model.service_account_list_all_of import ServiceAccountListAllOf
from dimakis_test_kafka_mgmt_sdk.model.service_account_list_item import ServiceAccountListItem
globals()['ServiceAccountListAllOf'] = ServiceAccountListAllOf
globals()['ServiceAccountListItem'] = ServiceAccountListItem
from dimakis_test_kafka_mgmt_sdk.model.service_account_list import ServiceAccountList


class TestServiceAccountList(unittest.TestCase):
    """ServiceAccountList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceAccountList(self):
        """Test ServiceAccountList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceAccountList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
