"""
    Red Hat Openshift SmartEvents Fleet Manager

    The API exposed by the fleet manager of the SmartEvents service.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: openbridge-dev@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_smart_events_mgmt_sdk
from rhoas_smart_events_mgmt_sdk.model.bridge_error_type import BridgeErrorType
globals()['BridgeErrorType'] = BridgeErrorType
from rhoas_smart_events_mgmt_sdk.model.bridge_error_instance import BridgeErrorInstance


class TestBridgeErrorInstance(unittest.TestCase):
    """BridgeErrorInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBridgeErrorInstance(self):
        """Test BridgeErrorInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BridgeErrorInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
