"""
    Red Hat Openshift SmartEvents Fleet Manager

    The API exposed by the fleet manager of the SmartEvents service.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: openbridge-dev@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dimakis_test_smart_events_mgmt_sdk
from dimakis_test_smart_events_mgmt_sdk.model.cloud_region_response import CloudRegionResponse
globals()['CloudRegionResponse'] = CloudRegionResponse
from dimakis_test_smart_events_mgmt_sdk.model.cloud_region_list_response import CloudRegionListResponse


class TestCloudRegionListResponse(unittest.TestCase):
    """CloudRegionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRegionListResponse(self):
        """Test CloudRegionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudRegionListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
