"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_mgmt_client
from kafka_mgmt_client.model.cloud_provider import CloudProvider
globals()['CloudProvider'] = CloudProvider
from kafka_mgmt_client.model.cloud_provider_list_all_of import CloudProviderListAllOf


class TestCloudProviderListAllOf(unittest.TestCase):
    """CloudProviderListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudProviderListAllOf(self):
        """Test CloudProviderListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudProviderListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
