"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import connector_management_sdk
from connector_management_sdk.model.connector_cluster_status_status import ConnectorClusterStatusStatus
globals()['ConnectorClusterStatusStatus'] = ConnectorClusterStatusStatus
from connector_management_sdk.model.connector_cluster_status import ConnectorClusterStatus


class TestConnectorClusterStatus(unittest.TestCase):
    """ConnectorClusterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorClusterStatus(self):
        """Test ConnectorClusterStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorClusterStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
