# flake8: noqa

"""
    Service Registry Management API

    Service Registry Management API is a REST API for managing Service Registry instances. Service Registry is a datastore for event schemas and API designs, which is based on the open source Apicurio Registry project.  # noqa: E501

    The version of the OpenAPI document: 0.0.6
    Contact: rhosak-eval-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from dimakis_test_service_registry_mgmt_sdk.api_client import ApiClient

# import Configuration
from dimakis_test_service_registry_mgmt_sdk.configuration import Configuration

# import exceptions
from dimakis_test_service_registry_mgmt_sdk.exceptions import OpenApiException
from dimakis_test_service_registry_mgmt_sdk.exceptions import ApiAttributeError
from dimakis_test_service_registry_mgmt_sdk.exceptions import ApiTypeError
from dimakis_test_service_registry_mgmt_sdk.exceptions import ApiValueError
from dimakis_test_service_registry_mgmt_sdk.exceptions import ApiKeyError
from dimakis_test_service_registry_mgmt_sdk.exceptions import ApiException
