"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_instance_sdk
from kafka_instance_sdk.model.error import Error
globals()['Error'] = Error
from kafka_instance_sdk.model.error_list_all_of import ErrorListAllOf


class TestErrorListAllOf(unittest.TestCase):
    """ErrorListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorListAllOf(self):
        """Test ErrorListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
