"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.list import List
from account_management_sdk.model.reserved_resource import ReservedResource
from account_management_sdk.model.reserved_resource_list_all_of import ReservedResourceListAllOf
globals()['List'] = List
globals()['ReservedResource'] = ReservedResource
globals()['ReservedResourceListAllOf'] = ReservedResourceListAllOf
from account_management_sdk.model.reserved_resource_list import ReservedResourceList


class TestReservedResourceList(unittest.TestCase):
    """ReservedResourceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReservedResourceList(self):
        """Test ReservedResourceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReservedResourceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
