"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.account_group_assignment import AccountGroupAssignment
from account_management_sdk.model.account_group_assignment_list_all_of import AccountGroupAssignmentListAllOf
from account_management_sdk.model.list import List
globals()['AccountGroupAssignment'] = AccountGroupAssignment
globals()['AccountGroupAssignmentListAllOf'] = AccountGroupAssignmentListAllOf
globals()['List'] = List
from account_management_sdk.model.account_group_assignment_list import AccountGroupAssignmentList


class TestAccountGroupAssignmentList(unittest.TestCase):
    """AccountGroupAssignmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountGroupAssignmentList(self):
        """Test AccountGroupAssignmentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountGroupAssignmentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
