"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.notification_contact_create_request import NotificationContactCreateRequest


class TestNotificationContactCreateRequest(unittest.TestCase):
    """NotificationContactCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationContactCreateRequest(self):
        """Test NotificationContactCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationContactCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
