"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.subscription_metric_all_of import SubscriptionMetricAllOf
globals()['SubscriptionMetricAllOf'] = SubscriptionMetricAllOf
from account_management_sdk.model.subscription_metric import SubscriptionMetric


class TestSubscriptionMetric(unittest.TestCase):
    """SubscriptionMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionMetric(self):
        """Test SubscriptionMetric"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionMetric()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
