"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.capability import Capability
from account_management_sdk.model.label import Label
globals()['Capability'] = Capability
globals()['Label'] = Label
from account_management_sdk.model.organization_all_of import OrganizationAllOf


class TestOrganizationAllOf(unittest.TestCase):
    """OrganizationAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationAllOf(self):
        """Test OrganizationAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
