"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.landing_page_ctl_item_shape import LandingPageCTLItemShape
globals()['LandingPageCTLItemShape'] = LandingPageCTLItemShape
from account_management_sdk.model.landing_page_ctl_item import LandingPageCTLItem


class TestLandingPageCTLItem(unittest.TestCase):
    """LandingPageCTLItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLandingPageCTLItem(self):
        """Test LandingPageCTLItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LandingPageCTLItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
