"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.quota_rules_all_of import QuotaRulesAllOf
globals()['ObjectReference'] = ObjectReference
globals()['QuotaRulesAllOf'] = QuotaRulesAllOf
from account_management_sdk.model.quota_rules import QuotaRules


class TestQuotaRules(unittest.TestCase):
    """QuotaRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaRules(self):
        """Test QuotaRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuotaRules()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
