"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.quota_all_of import QuotaAllOf
globals()['ObjectReference'] = ObjectReference
globals()['QuotaAllOf'] = QuotaAllOf
from account_management_sdk.model.quota import Quota


class TestQuota(unittest.TestCase):
    """Quota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuota(self):
        """Test Quota"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Quota()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
