"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.cloud_resource import CloudResource
from account_management_sdk.model.cloud_resource_list_all_of import CloudResourceListAllOf
from account_management_sdk.model.list import List
globals()['CloudResource'] = CloudResource
globals()['CloudResourceListAllOf'] = CloudResourceListAllOf
globals()['List'] = List
from account_management_sdk.model.cloud_resource_list import CloudResourceList


class TestCloudResourceList(unittest.TestCase):
    """CloudResourceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudResourceList(self):
        """Test CloudResourceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudResourceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
