"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.list import List
from account_management_sdk.model.role_binding import RoleBinding
from account_management_sdk.model.role_binding_list_all_of import RoleBindingListAllOf
globals()['List'] = List
globals()['RoleBinding'] = RoleBinding
globals()['RoleBindingListAllOf'] = RoleBindingListAllOf
from account_management_sdk.model.role_binding_list import RoleBindingList


class TestRoleBindingList(unittest.TestCase):
    """RoleBindingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleBindingList(self):
        """Test RoleBindingList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleBindingList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
