"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.deleted_subscription import DeletedSubscription
globals()['DeletedSubscription'] = DeletedSubscription
from account_management_sdk.model.deleted_subscription_list_all_of import DeletedSubscriptionListAllOf


class TestDeletedSubscriptionListAllOf(unittest.TestCase):
    """DeletedSubscriptionListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeletedSubscriptionListAllOf(self):
        """Test DeletedSubscriptionListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeletedSubscriptionListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
