"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.role_binding_all_of import RoleBindingAllOf
globals()['ObjectReference'] = ObjectReference
globals()['RoleBindingAllOf'] = RoleBindingAllOf
from account_management_sdk.model.role_binding import RoleBinding


class TestRoleBinding(unittest.TestCase):
    """RoleBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleBinding(self):
        """Test RoleBinding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleBinding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
