"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.cluster_metrics_nodes import ClusterMetricsNodes
from account_management_sdk.model.cluster_resource import ClusterResource
from account_management_sdk.model.cluster_upgrade import ClusterUpgrade
globals()['ClusterMetricsNodes'] = ClusterMetricsNodes
globals()['ClusterResource'] = ClusterResource
globals()['ClusterUpgrade'] = ClusterUpgrade
from account_management_sdk.model.one_metric import OneMetric


class TestOneMetric(unittest.TestCase):
    """OneMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneMetric(self):
        """Test OneMetric"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OneMetric()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
