"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.quota_rules import QuotaRules
globals()['QuotaRules'] = QuotaRules
from account_management_sdk.model.quota_rules_list_all_of import QuotaRulesListAllOf


class TestQuotaRulesListAllOf(unittest.TestCase):
    """QuotaRulesListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaRulesListAllOf(self):
        """Test QuotaRulesListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuotaRulesListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
