"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.summary_vector_all_of import SummaryVectorAllOf
globals()['SummaryVectorAllOf'] = SummaryVectorAllOf
from account_management_sdk.model.summary_vector import SummaryVector


class TestSummaryVector(unittest.TestCase):
    """SummaryVector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummaryVector(self):
        """Test SummaryVector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SummaryVector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
