"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.cloud_resource_all_of import CloudResourceAllOf
from account_management_sdk.model.object_reference import ObjectReference
globals()['CloudResourceAllOf'] = CloudResourceAllOf
globals()['ObjectReference'] = ObjectReference
from account_management_sdk.model.cloud_resource import CloudResource


class TestCloudResource(unittest.TestCase):
    """CloudResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudResource(self):
        """Test CloudResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
