"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.role_binding_request import RoleBindingRequest
globals()['RoleBindingRequest'] = RoleBindingRequest
from account_management_sdk.model.role_binding_create_request import RoleBindingCreateRequest


class TestRoleBindingCreateRequest(unittest.TestCase):
    """RoleBindingCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleBindingCreateRequest(self):
        """Test RoleBindingCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleBindingCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
