"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.capability_all_of import CapabilityAllOf
from account_management_sdk.model.object_reference import ObjectReference
globals()['CapabilityAllOf'] = CapabilityAllOf
globals()['ObjectReference'] = ObjectReference
from account_management_sdk.model.capability import Capability


class TestCapability(unittest.TestCase):
    """Capability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapability(self):
        """Test Capability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Capability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
