"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.consumed_quota import ConsumedQuota
from account_management_sdk.model.consumed_quota_list_all_of import ConsumedQuotaListAllOf
from account_management_sdk.model.list import List
globals()['ConsumedQuota'] = ConsumedQuota
globals()['ConsumedQuotaListAllOf'] = ConsumedQuotaListAllOf
globals()['List'] = List
from account_management_sdk.model.consumed_quota_list import ConsumedQuotaList


class TestConsumedQuotaList(unittest.TestCase):
    """ConsumedQuotaList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumedQuotaList(self):
        """Test ConsumedQuotaList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsumedQuotaList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
