"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.label import Label
globals()['Label'] = Label
from account_management_sdk.model.label_list_all_of import LabelListAllOf


class TestLabelListAllOf(unittest.TestCase):
    """LabelListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelListAllOf(self):
        """Test LabelListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
