"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.cluster_transfer_all_of import ClusterTransferAllOf


class TestClusterTransferAllOf(unittest.TestCase):
    """ClusterTransferAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterTransferAllOf(self):
        """Test ClusterTransferAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterTransferAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
