"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.account_group_request_all_of import AccountGroupRequestAllOf
from account_management_sdk.model.object_reference import ObjectReference
globals()['AccountGroupRequestAllOf'] = AccountGroupRequestAllOf
globals()['ObjectReference'] = ObjectReference
from account_management_sdk.model.account_group_request import AccountGroupRequest


class TestAccountGroupRequest(unittest.TestCase):
    """AccountGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountGroupRequest(self):
        """Test AccountGroupRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountGroupRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
