"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.capability import Capability
from account_management_sdk.model.label import Label
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.organization_all_of import OrganizationAllOf
globals()['Capability'] = Capability
globals()['Label'] = Label
globals()['ObjectReference'] = ObjectReference
globals()['OrganizationAllOf'] = OrganizationAllOf
from account_management_sdk.model.organization import Organization


class TestOrganization(unittest.TestCase):
    """Organization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganization(self):
        """Test Organization"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Organization()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
