"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.list import List
from account_management_sdk.model.sku_rules import SkuRules
from account_management_sdk.model.sku_rules_list_all_of import SkuRulesListAllOf
globals()['List'] = List
globals()['SkuRules'] = SkuRules
globals()['SkuRulesListAllOf'] = SkuRulesListAllOf
from account_management_sdk.model.sku_rules_list import SkuRulesList


class TestSkuRulesList(unittest.TestCase):
    """SkuRulesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkuRulesList(self):
        """Test SkuRulesList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SkuRulesList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
