"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.error import Error
from account_management_sdk.model.error_list_all_of import ErrorListAllOf
from account_management_sdk.model.list import List
globals()['Error'] = Error
globals()['ErrorListAllOf'] = ErrorListAllOf
globals()['List'] = List
from account_management_sdk.model.error_list import ErrorList


class TestErrorList(unittest.TestCase):
    """ErrorList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorList(self):
        """Test ErrorList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
