"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.quota_cost import QuotaCost
globals()['QuotaCost'] = QuotaCost
from account_management_sdk.model.quota_cost_list_all_of import QuotaCostListAllOf


class TestQuotaCostListAllOf(unittest.TestCase):
    """QuotaCostListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaCostListAllOf(self):
        """Test QuotaCostListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuotaCostListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
