"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.list import List
from account_management_sdk.model.subscription import Subscription
from account_management_sdk.model.subscription_list_all_of import SubscriptionListAllOf
globals()['List'] = List
globals()['Subscription'] = Subscription
globals()['SubscriptionListAllOf'] = SubscriptionListAllOf
from account_management_sdk.model.subscription_list import SubscriptionList


class TestSubscriptionList(unittest.TestCase):
    """SubscriptionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionList(self):
        """Test SubscriptionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
