"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.object_reference import ObjectReference
globals()['ObjectReference'] = ObjectReference
from account_management_sdk.model.reserved_resource_all_of import ReservedResourceAllOf


class TestReservedResourceAllOf(unittest.TestCase):
    """ReservedResourceAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReservedResourceAllOf(self):
        """Test ReservedResourceAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReservedResourceAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
