"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.account_reference import AccountReference
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.subscription_role_binding_all_of import SubscriptionRoleBindingAllOf
globals()['AccountReference'] = AccountReference
globals()['ObjectReference'] = ObjectReference
globals()['SubscriptionRoleBindingAllOf'] = SubscriptionRoleBindingAllOf
from account_management_sdk.model.subscription_role_binding import SubscriptionRoleBinding


class TestSubscriptionRoleBinding(unittest.TestCase):
    """SubscriptionRoleBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionRoleBinding(self):
        """Test SubscriptionRoleBinding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionRoleBinding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
