"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.registry import Registry
globals()['Registry'] = Registry
from account_management_sdk.model.registry_list_all_of import RegistryListAllOf


class TestRegistryListAllOf(unittest.TestCase):
    """RegistryListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryListAllOf(self):
        """Test RegistryListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
