"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.terms_review import TermsReview


class TestTermsReview(unittest.TestCase):
    """TermsReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermsReview(self):
        """Test TermsReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TermsReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
