"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.object_reference import ObjectReference
from account_management_sdk.model.reserved_resource_all_of import ReservedResourceAllOf
globals()['ObjectReference'] = ObjectReference
globals()['ReservedResourceAllOf'] = ReservedResourceAllOf
from account_management_sdk.model.reserved_resource import ReservedResource


class TestReservedResource(unittest.TestCase):
    """ReservedResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReservedResource(self):
        """Test ReservedResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReservedResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
