"""
    Account Management Service API

    Manage user subscriptions and clusters  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import account_management_sdk
from account_management_sdk.model.list import List
from account_management_sdk.model.sku import SKU
from account_management_sdk.model.sku_list_all_of import SkuListAllOf
globals()['List'] = List
globals()['SKU'] = SKU
globals()['SkuListAllOf'] = SkuListAllOf
from account_management_sdk.model.sku_list import SkuList


class TestSkuList(unittest.TestCase):
    """SkuList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkuList(self):
        """Test SkuList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SkuList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
