"""
    Service Accounts API Documentation

    This is the API documentation for Service Accounts  # noqa: E501

    The version of the OpenAPI document: 5.0.19
    Contact: it-user-team-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_service_accounts_mgmt_sdk
from rhoas_service_accounts_mgmt_sdk.api.service_accounts_api import ServiceAccountsApi  # noqa: E501


class TestServiceAccountsApi(unittest.TestCase):
    """ServiceAccountsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_account(self):
        """Test case for create_service_account

        Create service account  # noqa: E501
        """
        pass

    def test_delete_service_account(self):
        """Test case for delete_service_account

        Delete service account by id  # noqa: E501
        """
        pass

    def test_get_service_account(self):
        """Test case for get_service_account

        Get service account by id  # noqa: E501
        """
        pass

    def test_get_service_accounts(self):
        """Test case for get_service_accounts

        List all service accounts  # noqa: E501
        """
        pass

    def test_reset_service_account_secret(self):
        """Test case for reset_service_account_secret

        Reset service account secret by id  # noqa: E501
        """
        pass

    def test_update_service_account(self):
        """Test case for update_service_account

        Update service account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
