"""
    Service Accounts API Documentation

    This is the API documentation for Service Accounts  # noqa: E501

    The version of the OpenAPI document: 5.0.19
    Contact: it-user-team-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_service_accounts_mgmt_sdk
from rhoas_service_accounts_mgmt_sdk.model.validation_exception_data import ValidationExceptionData


class TestValidationExceptionData(unittest.TestCase):
    """ValidationExceptionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidationExceptionData(self):
        """Test ValidationExceptionData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidationExceptionData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
