"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.13.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.acl_operation import AclOperation
from rhoas_kafka_instance_sdk.model.acl_pattern_type import AclPatternType
from rhoas_kafka_instance_sdk.model.acl_permission_type import AclPermissionType
from rhoas_kafka_instance_sdk.model.acl_resource_type import AclResourceType
globals()['AclOperation'] = AclOperation
globals()['AclPatternType'] = AclPatternType
globals()['AclPermissionType'] = AclPermissionType
globals()['AclResourceType'] = AclResourceType
from rhoas_kafka_instance_sdk.model.acl_binding_all_of import AclBindingAllOf


class TestAclBindingAllOf(unittest.TestCase):
    """AclBindingAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAclBindingAllOf(self):
        """Test AclBindingAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AclBindingAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
