"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dimakis_test_kafka_instance_sdk
from dimakis_test_kafka_instance_sdk.model.record_all_of import RecordAllOf


class TestRecordAllOf(unittest.TestCase):
    """RecordAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordAllOf(self):
        """Test RecordAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecordAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
