"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dimakis_test_kafka_instance_sdk
from dimakis_test_kafka_instance_sdk.model.consumer_group_state import ConsumerGroupState


class TestConsumerGroupState(unittest.TestCase):
    """ConsumerGroupState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumerGroupState(self):
        """Test ConsumerGroupState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsumerGroupState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
