"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dimakis_test_kafka_instance_sdk
from dimakis_test_kafka_instance_sdk.model.list import List
from dimakis_test_kafka_instance_sdk.model.list_deprecated_all_of import ListDeprecatedAllOf
globals()['List'] = List
globals()['ListDeprecatedAllOf'] = ListDeprecatedAllOf
from dimakis_test_kafka_instance_sdk.model.list_deprecated import ListDeprecated


class TestListDeprecated(unittest.TestCase):
    """ListDeprecated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDeprecated(self):
        """Test ListDeprecated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListDeprecated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
