"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.acl_pattern_type_filter import AclPatternTypeFilter


class TestAclPatternTypeFilter(unittest.TestCase):
    """AclPatternTypeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAclPatternTypeFilter(self):
        """Test AclPatternTypeFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AclPatternTypeFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
