"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.13.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.consumer import Consumer


class TestConsumer(unittest.TestCase):
    """Consumer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumer(self):
        """Test Consumer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Consumer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
