"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.api.errors_api import ErrorsApi  # noqa: E501


class TestErrorsApi(unittest.TestCase):
    """ErrorsApi unit test stubs"""

    def setUp(self):
        self.api = ErrorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_error(self):
        """Test case for get_error

        Get an error by its unique ID  # noqa: E501
        """
        pass

    def test_get_errors(self):
        """Test case for get_errors

        Get list of errors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
