"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.13.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.topic import Topic
globals()['Topic'] = Topic
from rhoas_kafka_instance_sdk.model.topics_list_all_of import TopicsListAllOf


class TestTopicsListAllOf(unittest.TestCase):
    """TopicsListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopicsListAllOf(self):
        """Test TopicsListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TopicsListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
