"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.consumer_group_metrics import ConsumerGroupMetrics


class TestConsumerGroupMetrics(unittest.TestCase):
    """ConsumerGroupMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumerGroupMetrics(self):
        """Test ConsumerGroupMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsumerGroupMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
