"""
    Kafka Instance API

    API for interacting with Kafka Instance. Includes Produce, Consume and Admin APIs  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_instance_sdk
from rhoas_kafka_instance_sdk.model.acl_permission_type_filter import AclPermissionTypeFilter


class TestAclPermissionTypeFilter(unittest.TestCase):
    """AclPermissionTypeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAclPermissionTypeFilter(self):
        """Test AclPermissionTypeFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AclPermissionTypeFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
