# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from connector_management_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from connector_management_sdk.model.addon_parameter import AddonParameter
from connector_management_sdk.model.addon_parameter_list import AddonParameterList
from connector_management_sdk.model.channel import Channel
from connector_management_sdk.model.connector import Connector
from connector_management_sdk.model.connector_cluster import ConnectorCluster
from connector_management_sdk.model.connector_cluster_list import ConnectorClusterList
from connector_management_sdk.model.connector_cluster_list_all_of import ConnectorClusterListAllOf
from connector_management_sdk.model.connector_cluster_meta import ConnectorClusterMeta
from connector_management_sdk.model.connector_cluster_request import ConnectorClusterRequest
from connector_management_sdk.model.connector_cluster_request_meta import ConnectorClusterRequestMeta
from connector_management_sdk.model.connector_cluster_state import ConnectorClusterState
from connector_management_sdk.model.connector_cluster_status import ConnectorClusterStatus
from connector_management_sdk.model.connector_cluster_status_status import ConnectorClusterStatusStatus
from connector_management_sdk.model.connector_configuration import ConnectorConfiguration
from connector_management_sdk.model.connector_desired_state import ConnectorDesiredState
from connector_management_sdk.model.connector_list import ConnectorList
from connector_management_sdk.model.connector_list_all_of import ConnectorListAllOf
from connector_management_sdk.model.connector_meta import ConnectorMeta
from connector_management_sdk.model.connector_meta_all_of import ConnectorMetaAllOf
from connector_management_sdk.model.connector_namespace import ConnectorNamespace
from connector_management_sdk.model.connector_namespace_all_of import ConnectorNamespaceAllOf
from connector_management_sdk.model.connector_namespace_eval_request import ConnectorNamespaceEvalRequest
from connector_management_sdk.model.connector_namespace_list import ConnectorNamespaceList
from connector_management_sdk.model.connector_namespace_list_all_of import ConnectorNamespaceListAllOf
from connector_management_sdk.model.connector_namespace_meta import ConnectorNamespaceMeta
from connector_management_sdk.model.connector_namespace_meta_all_of import ConnectorNamespaceMetaAllOf
from connector_management_sdk.model.connector_namespace_patch_request import ConnectorNamespacePatchRequest
from connector_management_sdk.model.connector_namespace_quota import ConnectorNamespaceQuota
from connector_management_sdk.model.connector_namespace_request import ConnectorNamespaceRequest
from connector_management_sdk.model.connector_namespace_request_all_of import ConnectorNamespaceRequestAllOf
from connector_management_sdk.model.connector_namespace_request_meta import ConnectorNamespaceRequestMeta
from connector_management_sdk.model.connector_namespace_state import ConnectorNamespaceState
from connector_management_sdk.model.connector_namespace_status import ConnectorNamespaceStatus
from connector_management_sdk.model.connector_namespace_tenant import ConnectorNamespaceTenant
from connector_management_sdk.model.connector_namespace_tenant_kind import ConnectorNamespaceTenantKind
from connector_management_sdk.model.connector_request import ConnectorRequest
from connector_management_sdk.model.connector_request_meta import ConnectorRequestMeta
from connector_management_sdk.model.connector_state import ConnectorState
from connector_management_sdk.model.connector_status import ConnectorStatus
from connector_management_sdk.model.connector_status_status import ConnectorStatusStatus
from connector_management_sdk.model.connector_type import ConnectorType
from connector_management_sdk.model.connector_type_all_of import ConnectorTypeAllOf
from connector_management_sdk.model.connector_type_list import ConnectorTypeList
from connector_management_sdk.model.connector_type_list_all_of import ConnectorTypeListAllOf
from connector_management_sdk.model.cpu_quota import CpuQuota
from connector_management_sdk.model.error import Error
from connector_management_sdk.model.kafka_connection_settings import KafkaConnectionSettings
from connector_management_sdk.model.list import List
from connector_management_sdk.model.memory_quota import MemoryQuota
from connector_management_sdk.model.object_meta import ObjectMeta
from connector_management_sdk.model.object_reference import ObjectReference
from connector_management_sdk.model.schema_registry_connection_settings import SchemaRegistryConnectionSettings
from connector_management_sdk.model.service_account import ServiceAccount
from connector_management_sdk.model.service_connection_settings import ServiceConnectionSettings
from connector_management_sdk.model.version_metadata import VersionMetadata
from connector_management_sdk.model.version_metadata_all_of import VersionMetadataAllOf
