"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.model.connector_namespace import ConnectorNamespace
from rhoas_connector_mgmt_sdk.model.connector_namespace_list_all_of import ConnectorNamespaceListAllOf
from rhoas_connector_mgmt_sdk.model.list import List
globals()['ConnectorNamespace'] = ConnectorNamespace
globals()['ConnectorNamespaceListAllOf'] = ConnectorNamespaceListAllOf
globals()['List'] = List
from rhoas_connector_mgmt_sdk.model.connector_namespace_list import ConnectorNamespaceList


class TestConnectorNamespaceList(unittest.TestCase):
    """ConnectorNamespaceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorNamespaceList(self):
        """Test ConnectorNamespaceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorNamespaceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
