"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.model.connector_namespace_status import ConnectorNamespaceStatus
from rhoas_connector_mgmt_sdk.model.connector_namespace_tenant import ConnectorNamespaceTenant
globals()['ConnectorNamespaceStatus'] = ConnectorNamespaceStatus
globals()['ConnectorNamespaceTenant'] = ConnectorNamespaceTenant
from rhoas_connector_mgmt_sdk.model.connector_namespace_all_of import ConnectorNamespaceAllOf


class TestConnectorNamespaceAllOf(unittest.TestCase):
    """ConnectorNamespaceAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorNamespaceAllOf(self):
        """Test ConnectorNamespaceAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorNamespaceAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
