"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.api.connectors_api import ConnectorsApi  # noqa: E501


class TestConnectorsApi(unittest.TestCase):
    """ConnectorsApi unit test stubs"""

    def setUp(self):
        self.api = ConnectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_connector(self):
        """Test case for create_connector

        Create a new connector  # noqa: E501
        """
        pass

    def test_delete_connector(self):
        """Test case for delete_connector

        Delete a connector  # noqa: E501
        """
        pass

    def test_get_connector(self):
        """Test case for get_connector

        Get a connector  # noqa: E501
        """
        pass

    def test_list_connectors(self):
        """Test case for list_connectors

        Returns a list of connector types  # noqa: E501
        """
        pass

    def test_patch_connector(self):
        """Test case for patch_connector

        Patch a connector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
