"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.model.service_account import ServiceAccount


class TestServiceAccount(unittest.TestCase):
    """ServiceAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceAccount(self):
        """Test ServiceAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
