"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.model.connector_namespace import ConnectorNamespace
globals()['ConnectorNamespace'] = ConnectorNamespace
from rhoas_connector_mgmt_sdk.model.connector_namespace_list_all_of import ConnectorNamespaceListAllOf


class TestConnectorNamespaceListAllOf(unittest.TestCase):
    """ConnectorNamespaceListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorNamespaceListAllOf(self):
        """Test ConnectorNamespaceListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorNamespaceListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
