"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.api.connector_types_api import ConnectorTypesApi  # noqa: E501


class TestConnectorTypesApi(unittest.TestCase):
    """ConnectorTypesApi unit test stubs"""

    def setUp(self):
        self.api = ConnectorTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_connector_type_by_id(self):
        """Test case for get_connector_type_by_id

        Get a connector type by id  # noqa: E501
        """
        pass

    def test_get_connector_type_labels(self):
        """Test case for get_connector_type_labels

        Returns a list of connector type labels  # noqa: E501
        """
        pass

    def test_get_connector_types(self):
        """Test case for get_connector_types

        Returns a list of connector types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
