"""
    Connector Management API

    Connector Management API is a REST API to manage connectors.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_connector_mgmt_sdk
from rhoas_connector_mgmt_sdk.model.connector_state import ConnectorState
globals()['ConnectorState'] = ConnectorState
from rhoas_connector_mgmt_sdk.model.connector_status_status import ConnectorStatusStatus


class TestConnectorStatusStatus(unittest.TestCase):
    """ConnectorStatusStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorStatusStatus(self):
        """Test ConnectorStatusStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorStatusStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
