"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.11.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kafka_mgmt_sdk
from kafka_mgmt_sdk.model.service_account_request import ServiceAccountRequest


class TestServiceAccountRequest(unittest.TestCase):
    """ServiceAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceAccountRequest(self):
        """Test ServiceAccountRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceAccountRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
